name: flatbeat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue: ^0.8.0
  image_picker: ^1.0.7
  http: ^1.2.0
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  intl: ^0.19.0
  path: ^1.8.3
  sqflite: ^2.3.2
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.10
  firebase_crashlytics: ^3.4.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/imagens/1231px-Flamengo_heart.svg.png
    - lib\assets\imagens\flamengo-imagem-1.png
